linters-settings:
  nlreturn:
    block-size: 2
  wsl:
    enforce-err-cuddling: true
  funlen:
    lines: 100
    statements: 50
  gomoddirectives:
    replace-allow-list:
      - maunium.net/go/mautrix # currently needed for the PoC to work (custom mautrix)

linters:
  enable-all: true
  disable:
    - ifshort # deprecated
    - nosnakecase # deprecated
    - interfacer # deprecated
    - deadcode # deprecated
    - exhaustivestruct # deprecated
    - varcheck # deprecated
    - structcheck # deprecated
    - maligned # deprecated
    - scopelint # deprecated
    - golint # deprecated
    - rowserrcheck # https://github.com/golangci/golangci-lint/issues/2649
    - sqlclosecheck # https://github.com/golangci/golangci-lint/issues/2649
    - wastedassign # https://github.com/golangci/golangci-lint/issues/2649
    - gomnd # we use status code numbers and for our use case it's not practical
    - godox # we have TODOs at this stage of the project, enable in future
    - forbidigo # we use things like fmt.Printf for debugging, enable in future
    - wsl # somehow this plugin causes more harm than use as it enables lots of things to be configured without causing spaghetti-code (grouping similar things together)
  fast: true
